development:
  adapter: mysql
  database: limecast_dev
  username: root
  password:
  encoding: utf8
  host:     localhost
  # socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  database: limecast_test
  username: root
  password:
  encoding: utf8
  host:     localhost
  # socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: limecast_production
  username: root
  password:
  encoding: utf8
  host:     localhost
  # socket: /var/run/mysqld/mysqld.sock

profiling:
  adapter: mysql
  database: limecast_profiling
  username: root
  password:
  encoding: utf8
  host:     localhost
  # socket: /var/run/mysqld/mysqld.sock

